### ISSUE TITLE
add configurable link to more info about files in tests

### ISSUE THREAD

**Issue by balmas** [Capitains/Hook#50]
It might be nice to be able to configure a "more info" link template for files in tests, so that viewers of the test results can have a better understanding of the context.

E.g. For files in the perseus corpus, with a link template like

`http://catalog.perseus.org/cite-collections/api/versions/search?version=URN`

and some way to specify instructions to take filenames and turn them into the URN 

you could provide links to the catalog data about a file

**Comment by balmas** [comment]
and speaking of URI templates, had no idea there was now an proposed standard for this https://tools.ietf.org/html/rfc6570

**Comment by PonteIneptique** [comment]
See probably with https://github.com/nigelsmall/urimagic/blob/master/urimagic/rfc6570.py

**Comment by PonteIneptique** [comment]
This is actually more complicated, because I forgot one point : we do not store the URN nor do we retrieve it during the test process. What we receive from HookTest is text logs and file name. That's all. This would mean HookTest rewriting, Hook UI, Model and controller rewriting (to take care of some new data)
